const ZOMBIES_DATA = {
  bo1: {title:"BLACK OPS",description:"Kino der Toten, Five, Ascension, Call of the Dead, Shangri-La et Moon.",cards:[["Kino der Toten","Plan, atouts, Pack-a-Punch, téléporteur et secrets."],["Ascension","Lander, Gersh Device, singes, Easter Egg et astuces."],["Moon","Wave Gun, excavateurs, hacker et gros secret."],["Call of the Dead","Scavenger, George Romero, radios et étapes principales."]]},
  bo2: {title:"BLACK OPS II",description:"TranZit, Nuketown, Die Rise, Mob of the Dead, Buried et Origins.",cards:[["Origins","Bâtons élémentaires, générateurs, robots, pelles, disques et Easter Egg."],["Die Rise","Sliquifier, pièces, ascenseurs, atouts et stratégie."],["Mob of the Dead","Blundergat, Acid Gat, Golden Spork, avion et pont."],["Buried","Paralyzer, Leroy, banque, labyrinthe, Time Bomb et secrets."],["TranZit","Bus, Jet Gun, turbine, Avogadro et raccourcis."],["Nuketown Zombies","Spawns aléatoires, compte à rebours et stratégie manches."]]},
  bo3: {title:"BLACK OPS III",description:"Shadows of Evil, The Giant, Der Eisendrache, Zetsubou, Gorod Krovi et Revelations.",cards:[["Der Eisendrache","Arcs élémentaires, Ragnarok DG-4 et Easter Egg."],["Shadows of Evil","Épée, Apothicon Servant, rituels et tram."],["Revelations","Secrets, masques, Keeper Protector et boss final."],["Zombies Chronicles","Guides remasterisés pour les maps classiques."]]},
  bo4: {title:"BLACK OPS 4",description:"Voyage of Despair, IX, Blood of the Dead, Classified et autres maps.",cards:[["IX","Death of Orion, challenges, temples et boss."],["Blood of the Dead","Spectral Shield, Hell's Retriever et Magmagat."],["Classified","Winters Howl, DEFCON et secrets."],["Ancient Evil","Gantelets, Pegasus et Easter Egg."]]},
  coldwar: {title:"COLD WAR",description:"Die Maschine, Firebase Z, Mauer der Toten, Forsaken et Outbreak.",cards:[["Die Maschine","D.I.E. Shockwave, upgrades, Aether et boss."],["Firebase Z","R.A.I. K-84, défense, Mimics et Easter Egg."],["Mauer der Toten","CRBR-S, Klaus, trains et étapes."],["Outbreak","Objectifs, régions, coffres, Orda et secrets."]]}
};
const GUIDE_STEPS = {
  "origins-ice-staff": {title:"Origins - Bâton de Glace",steps:["Récupérer le disque bleu près du générateur 2.","Trouver les 3 pièces du bâton en creusant quand il neige.","Prendre le gramophone et le disque noir pour accéder au Crazy Place.","Récupérer le cristal bleu, construire le bâton puis lancer l'amélioration.","Résoudre les symboles, tirer sur les pierres tombales et charger le bâton."]},
  "origins-map": {title:"Carte interactive Origins",steps:["Version prête pour ajouter une image de map.","On placera les points cliquables : atouts, générateurs, pelles, boîtes, disques et robots."]},
  "calculator": {title:"Calculateur Zombies",steps:["Déjà intégré dans la page Outils.","Tu peux entrer une manche et un nombre de joueurs pour obtenir une estimation simple."]}
};
